
// This file has been generated by the GUI designer. Do not modify.
namespace mainWindow
{
	public partial class MainWindow
	{
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.HScale hscale1;
		
		private global::Gtk.Fixed fixed9;
		
		private global::Gtk.Button button10;
		
		private global::Gtk.Button button11;
		
		private global::Gtk.Button button12;
		
		private global::Gtk.Button button13;
		
		private global::Gtk.Fixed fixed11;
		
		private global::Gtk.HScale hscale2;
		
		private global::Gtk.Button button15;
		
		private global::Gtk.Button button16;
		
		private global::Gtk.HScale hscale3;
		
		private global::Gtk.ToggleButton togglebutton2;
		
		private global::Gtk.ToggleButton togglebutton1;
		
		private global::Gtk.Fixed fixed10;
		
		private global::Gtk.Button button14;
		
		private global::Gtk.Button button19;
		
		private global::Gtk.Button button1;
		
		private global::Gtk.Button button2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget mainWindow.MainWindow
			this.Name = "mainWindow.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child mainWindow.MainWindow.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.vbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hscale1 = new global::Gtk.HScale (null);
			this.hscale1.CanFocus = true;
			this.hscale1.Name = "hscale1";
			this.hscale1.Adjustment.Upper = 100;
			this.hscale1.Adjustment.PageIncrement = 10;
			this.hscale1.Adjustment.StepIncrement = 1;
			this.hscale1.Adjustment.Value = 39.5804195804196;
			this.hscale1.DrawValue = false;
			this.hscale1.Digits = 0;
			this.hscale1.ValuePos = ((global::Gtk.PositionType)(2));
			this.vbox3.Add (this.hscale1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hscale1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.fixed9 = new global::Gtk.Fixed ();
			this.fixed9.Name = "fixed9";
			this.fixed9.HasWindow = false;
			// Container child fixed9.Gtk.Fixed+FixedChild
			this.button10 = new global::Gtk.Button ();
			this.button10.CanFocus = true;
			this.button10.Name = "button10";
			this.button10.UseStock = true;
			this.button10.UseUnderline = true;
			this.button10.FocusOnClick = false;
			this.button10.Relief = ((global::Gtk.ReliefStyle)(2));
			this.button10.Label = "gtk-media-stop";
			this.fixed9.Add (this.button10);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed9 [this.button10]));
			w3.X = 227;
			// Container child fixed9.Gtk.Fixed+FixedChild
			this.button11 = new global::Gtk.Button ();
			this.button11.CanFocus = true;
			this.button11.Name = "button11";
			this.button11.UseStock = true;
			this.button11.UseUnderline = true;
			this.button11.Relief = ((global::Gtk.ReliefStyle)(2));
			this.button11.Label = "gtk-media-previous";
			this.fixed9.Add (this.button11);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed9 [this.button11]));
			w4.X = 4;
			// Container child fixed9.Gtk.Fixed+FixedChild
			this.button12 = new global::Gtk.Button ();
			this.button12.CanFocus = true;
			this.button12.Name = "button12";
			this.button12.UseStock = true;
			this.button12.UseUnderline = true;
			this.button12.Relief = ((global::Gtk.ReliefStyle)(2));
			this.button12.Label = "gtk-media-play";
			this.fixed9.Add (this.button12);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed9 [this.button12]));
			w5.X = 108;
			// Container child fixed9.Gtk.Fixed+FixedChild
			this.button13 = new global::Gtk.Button ();
			this.button13.CanFocus = true;
			this.button13.Name = "button13";
			this.button13.UseStock = true;
			this.button13.UseUnderline = true;
			this.button13.Relief = ((global::Gtk.ReliefStyle)(2));
			this.button13.Label = "gtk-media-next";
			this.fixed9.Add (this.button13);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed9 [this.button13]));
			w6.X = 331;
			this.vbox3.Add (this.fixed9);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fixed9]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.fixed11 = new global::Gtk.Fixed ();
			this.fixed11.Name = "fixed11";
			this.fixed11.HasWindow = false;
			// Container child fixed11.Gtk.Fixed+FixedChild
			this.hscale2 = new global::Gtk.HScale (null);
			this.hscale2.WidthRequest = 150;
			this.hscale2.CanFocus = true;
			this.hscale2.Name = "hscale2";
			this.hscale2.Adjustment.Upper = 100;
			this.hscale2.Adjustment.PageIncrement = 10;
			this.hscale2.Adjustment.StepIncrement = 1;
			this.hscale2.DrawValue = false;
			this.hscale2.Digits = 0;
			this.hscale2.ValuePos = ((global::Gtk.PositionType)(2));
			this.fixed11.Add (this.hscale2);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed11 [this.hscale2]));
			w8.X = 116;
			// Container child fixed11.Gtk.Fixed+FixedChild
			this.button15 = new global::Gtk.Button ();
			this.button15.CanFocus = true;
			this.button15.Name = "button15";
			this.button15.UseUnderline = true;
			this.button15.Label = global::Mono.Unix.Catalog.GetString ("shuffle");
			global::Gtk.Image w9 = new global::Gtk.Image ();
			w9.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-sort-ascending", global::Gtk.IconSize.Menu);
			this.button15.Image = w9;
			this.fixed11.Add (this.button15);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed11 [this.button15]));
			w10.X = 1;
			// Container child fixed11.Gtk.Fixed+FixedChild
			this.button16 = new global::Gtk.Button ();
			this.button16.CanFocus = true;
			this.button16.Name = "button16";
			this.button16.UseUnderline = true;
			global::Gtk.Image w11 = new global::Gtk.Image ();
			w11.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-refresh", global::Gtk.IconSize.Menu);
			this.button16.Image = w11;
			this.fixed11.Add (this.button16);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed11 [this.button16]));
			w12.X = 82;
			// Container child fixed11.Gtk.Fixed+FixedChild
			this.hscale3 = new global::Gtk.HScale (null);
			this.hscale3.WidthRequest = 90;
			this.hscale3.CanFocus = true;
			this.hscale3.Name = "hscale3";
			this.hscale3.Adjustment.Upper = 100;
			this.hscale3.Adjustment.PageIncrement = 10;
			this.hscale3.Adjustment.StepIncrement = 1;
			this.hscale3.Adjustment.Value = 50;
			this.hscale3.DrawValue = false;
			this.hscale3.Digits = 0;
			this.hscale3.ValuePos = ((global::Gtk.PositionType)(2));
			this.fixed11.Add (this.hscale3);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed11 [this.hscale3]));
			w13.X = 269;
			// Container child fixed11.Gtk.Fixed+FixedChild
			this.togglebutton2 = new global::Gtk.ToggleButton ();
			this.togglebutton2.CanFocus = true;
			this.togglebutton2.Name = "togglebutton2";
			this.togglebutton2.UseUnderline = true;
			this.togglebutton2.Label = global::Mono.Unix.Catalog.GetString ("EQ");
			global::Gtk.Image w14 = new global::Gtk.Image ();
			w14.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-unindent", global::Gtk.IconSize.Menu);
			this.togglebutton2.Image = w14;
			this.fixed11.Add (this.togglebutton2);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed11 [this.togglebutton2]));
			w15.X = 410;
			// Container child fixed11.Gtk.Fixed+FixedChild
			this.togglebutton1 = new global::Gtk.ToggleButton ();
			this.togglebutton1.CanFocus = true;
			this.togglebutton1.Name = "togglebutton1";
			this.togglebutton1.UseUnderline = true;
			this.togglebutton1.Active = true;
			this.togglebutton1.Label = global::Mono.Unix.Catalog.GetString ("PL");
			global::Gtk.Image w16 = new global::Gtk.Image ();
			w16.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-sort-descending", global::Gtk.IconSize.Menu);
			this.togglebutton1.Image = w16;
			this.fixed11.Add (this.togglebutton1);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed11 [this.togglebutton1]));
			w17.X = 368;
			this.vbox3.Add (this.fixed11);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fixed11]));
			w18.Position = 3;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.fixed10 = new global::Gtk.Fixed ();
			this.fixed10.Name = "fixed10";
			this.fixed10.HasWindow = false;
			// Container child fixed10.Gtk.Fixed+FixedChild
			this.button14 = new global::Gtk.Button ();
			this.button14.CanFocus = true;
			this.button14.Name = "button14";
			this.button14.UseStock = true;
			this.button14.UseUnderline = true;
			this.button14.Relief = ((global::Gtk.ReliefStyle)(2));
			this.button14.Label = "gtk-open";
			this.fixed10.Add (this.button14);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed10 [this.button14]));
			w19.X = 4;
			// Container child fixed10.Gtk.Fixed+FixedChild
			this.button19 = new global::Gtk.Button ();
			this.button19.CanFocus = true;
			this.button19.Name = "button19";
			this.button19.UseUnderline = true;
			this.button19.Label = global::Mono.Unix.Catalog.GetString ("test");
			global::Gtk.Image w20 = new global::Gtk.Image ();
			w20.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-about", global::Gtk.IconSize.Menu);
			this.button19.Image = w20;
			this.fixed10.Add (this.button19);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed10 [this.button19]));
			w21.X = 250;
			// Container child fixed10.Gtk.Fixed+FixedChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString ("Очистить");
			global::Gtk.Image w22 = new global::Gtk.Image ();
			w22.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-clear", global::Gtk.IconSize.Menu);
			this.button1.Image = w22;
			this.fixed10.Add (this.button1);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed10 [this.button1]));
			w23.X = 156;
			// Container child fixed10.Gtk.Fixed+FixedChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString ("Folder");
			this.fixed10.Add (this.button2);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed10 [this.button2]));
			w24.X = 77;
			this.vbox3.Add (this.fixed10);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fixed10]));
			w25.Position = 4;
			w25.Expand = false;
			w25.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 456;
			this.DefaultHeight = 182;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.hscale1.ValueChanged += new global::System.EventHandler (this.OnHscale1ValueChanged);
			this.button10.Clicked += new global::System.EventHandler (this.OnButton10Clicked);
			this.button11.Clicked += new global::System.EventHandler (this.OnButton11Clicked);
			this.button12.Clicked += new global::System.EventHandler (this.OnButton12Clicked);
			this.button13.Clicked += new global::System.EventHandler (this.OnButton13Clicked);
			this.button15.Clicked += new global::System.EventHandler (this.OnButton15Clicked);
			this.button16.Clicked += new global::System.EventHandler (this.OnButton16Clicked);
			this.togglebutton1.Clicked += new global::System.EventHandler (this.OnTogglebutton1Clicked);
			this.button14.Clicked += new global::System.EventHandler (this.OnButton14Clicked);
			this.button19.Clicked += new global::System.EventHandler (this.OnButton19Clicked);
			this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
			this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
		}
	}
}
